- components/Nav.js
- components/ui/PageContainer.js
- stories/UserInfo.stories.jsx
- styles/theme.js
- implement small layout adjustments to allow nav and page container to be unified
> [WIL-38] Layout adjustments

- components/page-content/NetworkContent.js
- lib/utils/fake-data.js
@adelbalso lets look at this together!
> [WIL-76] Add show more functionality to filters

- api/search.js
- components/UserResultItem.js
- components/page-content/NetworkContent.js
- hooks/useSearch.js
- package.json
- yarn.lock
- Adds a search API (which hits production)
- adds a useSearch hook 
- update UI w/ controlled input and update state
> Directory: Implement Network Search API

- package-lock.json
- pages/advice/people/[userId]/decisions/[decisionId].js
- yarn.lock
• add stakeholder map in advice givers section
• include logic to display add button only in draft state
> [WIL-104] Build the advice givers section

- api/processes.js
- components/Task.js
- pages/ssj/[phase]/[milestone]/[task]/index.js
- pages/ssj/[phase]/[milestone]/index.js
- task component gets taskId
- use processesAPI to call process API endpoint
> Hookup Task Complete API

- components/Milestone.js
- components/Nav.js
- components/Task.js
- lib/useUserContext.js
- pages/login.js
- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- pages/ssj/index.js
- use the new `assigneeInfo` key to get profile picture
- sort tasks mapped on `[milestone]` to appear in order of `position`
> Cleanup and ui adjustments

- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- move the adding cta to a less obvious place
- build a form reset so the user can add multiple milestones in one session
> update add milestone form and ui

- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- add an api call to request the phase's to do milestones
- display the milestones a user "should" work on in the correct UI
> show the correct to do milestones on an up next milestone

- components/Milestone.js
- components/StatusChip.js
- components/Task.js
- components/ui/Icon.js
- pages/ssj/[phase]/index.js
- add an in progress section to the [phase] page
- update the `Milestone` component to support "in progress" status
- update the `StatusChip` component to support "in progress" status
- Update the icon choice to be more communicative  of phases
> build in progress status support

- pages/ssj/[phase]/index.js
- filter the data
- pass the data in as props
- update ui to accommodate
> filter returned data on phase page to show correct start considering milestones

- components/Milestone.js
- components/Nav.js
- components/Task.js
- components/ui/Icon.js
- pages/ssj/[phase]/index.js
- pages/ssj/index.js
- make copy updates to drawer actions in `Task`
- bonus: update the milestone progress preview on the phase page
> update copy to reflect taking on tasks, rather than assigning self

- components/InfoDrawer.js
- components/Milestone.js
- components/Task.js
- components/WorktimeChip.js
- components/ui/Icon.js
- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- styles/theme.js
- update the `EffortChip` component to be `WorktimeChip`
- update copy on task actions
- misc fake data removal
> update task to include worktime and misc copy changes

- pages/ssj/index.js
- request `dashboard` endpoint data and send as props
- adjustments to components to display UI correctly
> hook up phase and category progress card

- components/Resource.js
- pages/ssj/index.js
- draft up maggie's content as json
- build new `WaysToWorkCard` component
- move state of view modal into component so scoped correctly
> build the ways to work together content

- pages/ssj/index.js
- update key so link works as expected
> pass correct key to PhaseProgressCard on ssj/index

- pages/ssj/index.js
- pass included documents to tasks on dashboard
> Pass correct data into tasks on dashboard

- pages/ssj/view-all.js
- Shows milestones by category
- Shows assigned tasks
- Shows resources by category
> Build the view all page

- components/Task.js
- pages/ssj/index.js
- added state to handle visibility
- pass prop to `Task` to specify when it should be removed from view
- adjust the `handleTaskComplete` function to remove task from view when appropriate
> Build removing task from view when complete in certain contexts

- api/ssj.js
1. Set expected start date. Date should be in "yyyy-mm-dd" format.
2. Grab team info. Response should look something like this:
```
{
"hasPartner": false,
"expectedStartDate": null,
"team": [
{
"data": {
"id": "6994-b92e",
"type": "person",
"attributes": {
"email": "amos_bartell@feeney.io",
"firstName": "Winnifred",
"middleName": null,
"lastName": "Heller",
"phone": "990.446.9843",
"journeyState": null,
"personalEmail": null,
"about": null,
"primaryLanguage": null,
"updatedAt": "2023-03-01T16:17:28.179Z",
"imageUrl": "https://avatars.githubusercontent.com/u/1683182?v=4",
"roleList": []
},
"relationships": {
"schools": {
"data": []
},
"schoolRelationships": {
"data": []
},
"address": {
"data": null
}
}
},
"included": []
}
]
}
```
> Setup api calls related to team

- pages/ssj/milestones.js
> Add data grouped by phase

- components/Milestone.js
- components/PhaseChip.js
- components/Task.js
- pages/ssj/index.js
- pages/ssj/milestones.js
- pages/ssj/resources.js
- pages/ssj/to-do-list.js
Including
- `/milestones`
- `/resources`
- `/to-do-list`
> Updates to the UI following api updates for new pages

- components/Task.js
- pages/ssj/to-do-list.js
- Add a `processName` prop to the `Task` component and use it to conditionally render the value
- Filter the included processes from the api response and pass to the frontend.
> pass the included process name to the task and display it when in to do list

- pages/ssj/to-do-list.js
-add a filter to only grab processes from included array
> Fix error on `to-do-list` where process id not found

- package.json
- pages/_app.js
- yarn.lock
- add `nprogress` package
- provide nprogress package elements with router information on `app.js`
> Add progress bar loader for page transitions

- components/Nav.js
- pages/ssj/[phase]/index.js
- change email copy
- remove "start considering" section and data
> change feedback email and udpate phase page to remove start considering

- components/Task.js
- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- pages/ssj/to-do-list.js
- Build `removeStep` function which splices the task from the targeted taskId matches the item's id
- Pass function into `Task` and call in appropriate handlers
- remove previous attempt
> Build function to remove tasks from list as complete in to do list

- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- comment out the ui for adding and editing milestones
> Remove add/edit milestones ui everywhere

- components/InfoDrawer.js
- Adjust `InfoDrawer` styles to support scrolling content when covered by actions
- Adjust order of "resources" vs "about" so that about comes first
- Adjust render condition for worktime to not show "0" when empty
> InfoDrawer improvements

- pages/ssj/index.js
- Remove occurrences of "ETL" and instead spell out "Emerging Teacher Leader"
- Update style of progress indicator to show only completed
- Remove "hub" from context section at top
- Remove "add message" field from add partner form
> Misc updates to the dashboard 

- components/ui/PageContainer.js
- components/ui/Spinner.js
- components/ui/index.js
- The PageContainer component now accepts an isLoading prop to show a spinner
> Build Progress Spinner UI

- pages/welcome/add-profile-info.js
Reverts keithtom/wildflower-journey-ui#155
> Revert "temporarily remove filepond plugin from onboarding and replace with native html input"

- api/people.js
- components/Header.js
- lib/rails-filechecksum.js
- lib/useUserContext.js
- lib/utils/baseUrl.js
- package.json
- pages/login.js
- pages/ssj/[phase]/index.js
- pages/ssj/index.js
- pages/ssj/milestones.js
- pages/ssj/resources.js
- pages/ssj/to-do-list.js
- pages/welcome/add-profile-info.js
- pages/welcome/confirm-demographic-info.js
- pages/welcome/confirm-your-details.js
- yarn.lock
1. Removes harded workflowID. When user signs in, it's set as a cookie. 
2. Update person's information
3. Upload's image url, and views it right away w/ out refresh
BE PR: https://github.com/keithtom/wildflower-platform/pull/69/files
> Onboarding new user

- components/Header.js
- pages/login.js
- pages/ssj/[phase]/[milestone]/index.js
- pages/ssj/[phase]/index.js
- pages/ssj/index.js
- pages/ssj/milestones.js
- pages/ssj/resources.js
- pages/ssj/to-do-list.js
- add a cookie on login for the user's current phase
- remove unused or old api calls throughout ssj routes
> Remove unused code and api calls in SSJ routes

- components/ui/PageContainer.js
- pages/welcome/add-profile-info.js
- pages/welcome/confirm-demographic-info.js
- pages/welcome/confirm-your-details.js
- pages/welcome/create-password.js
- pages/welcome/new-etl.js
- use the `currentUser` object where available to populate Operations Guide data
- Update validations to watch the fields and show the correct data when a user "edits"
> Add real user data to onboarding, form validation improvements

- components/Header.js
- components/InfoDrawer.js
- components/Nav.js
- components/ui/Link.js
- components/ui/MultiSelect.js
- components/ui/NavLink.js
- components/ui/Select.js
- pages/ssj/index.js
- Fix info drawer actions to be sticky to bottom and allow scrolling
- Fix dropdown (select, multiselect) arrows not being clickable
- Fix anticipated open date in the add open date modal not being correct (was a time zone issue)
- Fix visual style of user menu navitems
> Bug fixes throughout

- pages/login.js
- add button and event handler for requesting a link to login
> Update login page with UI for request a link option

- api/registrations.js
- pages/welcome/add-profile-info.js
Some small fixes to get adding new password to work and uploading to S3.
> Auth header for logging in, don't need it when uploading to s3

- api/steps.js
- components/Task.js
hookup selecting decision option to backend
> hookup selecting decision option to backend

- api/users.js
- pages/login.js
1. Set the jwt tokens and all other cookies to expire in 30 days
2. Set up api request to send email with login link.
> Login via link

- .env
- pages/ssj/index.js
- add logic around when to reset the user inputted value
> QA: Fix the date select modal on the dashboard

- pages/ssj/index.js
> Access partner information

- components/InfoDrawer.js
- components/Task.js
- Do not show "assignee" attribute if no assignee in `InfoDrawer`
- Include "check" badge on avatar in `Task` to indicate who has completed the task
> Fixes to assignee UI on Task and InfoDrawer

- pages/ssj/index.js
- update the progress card image styles
> Fix the progress card images on dashboard

- components/Task.js
- components/ui/Chip.js
- yarn.lock
- specify that a default value for variant in chip
> Fix: MUI Capitalize error
